name: Deploy to Staging

on:
  push:
    branches: [main]

jobs:
  redeploy_application:
    runs-on: ubuntu-latest
    name: Deploying the application to staging
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.STAGING_SECRET }}" > ~/ssh_key
          chmod 600 ~/ssh_key

      - name: SSH into server and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@3.108.58.241 << 'EOF'
            # Source environment setup
            source ~/.bashrc
            source ~/.nvm/nvm.sh

            # Ensure Node.js and pnpm are accessible
            export PATH="$HOME/.nvm/versions/node/v22.14.0/bin:$PATH"
            echo "Node version: $(node -v)"
            echo "pnpm version: $(pnpm -v)"

            # Deployment commands
            cd monorepo-test
            git pull
            pnpm install
            pnpm run build
            pm2 restart fe-server
            pm2 restart http-server
            pm2 restart ws-server
          EOF
