name : Deploy to Staging

on:
  push:
    branches:
      - "main"

jobs : 
  redeploy_application :
    name : Deploying the application to staging
    steps : 
      - name : ssh into server
      - run : | 
          echo ${{secrets.STAGING_SECRET}} &> ~/ssh_key
          ssh -i ~/ssh_key ubuntu@3.108.58.241
          cd monorepo-test && git pull
          pnpm install
          pnpm run build
          pm2 restart fe-server
          pm2 restart http-server
          pm2 restart ws-server
