name: Deploy to Staging

on:
  push:
    branches: [main]

jobs:
  redeploy_application:
    runs-on: ubuntu-latest
    name: Deploying the application to staging
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.STAGING_SECRET }}" > ~/ssh_key
          chmod 700 ~/ssh_key

      - name: SSH into server and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@3.108.58.241 << 'EOF'
            cd monorepo-test
            git pull
            pnpm install
            pnpm run build
            pm2 restart fe-server
            pm2 restart http-server
            pm2 restart ws-server
          EOF
